dataSource:
  driverClassName: com.mysql.jdbc.Driver
  dbCreate: update
  username: root
  password: root

environments:
  development:
    dataSource:
      dbCreate: create
      url: "jdbc:mysql://localhost:3306/student?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"